### ISSUE TITLE
Evaluation von Rider

### ISSUE THREAD

**Issue by MBrill** [VRLAB-HSKL/VRDemos#12]
Rider ist scheinbar interessante Alternative für C#-Entwicklung in Unity an Stelle von Visual Studio. 

Wir schauen die IDE an und schreiben, falls wir das sinnvoll halten, in das Wiki.

Kritierien:
- frei verfügbar?
- stabil?
- Zusammenspiel mit Unity?

**Comment by Jub42** [comment]
JetBrains bietet unter folgendem Link eine kostenlose Lizenz für Lehrende und Lernende an:
[Rider Lizenz](https://www.jetbrains.com/rider/buy/#discounts?billing=yearly)

Rider bietet Vielzahl an Quality of Life Features, darunter:

- Mit 2x Shift hat der Nutzer die Möglichkeit mit Hilfe einer Suchfunktion durch das Projekt zu navigieren. Hierbei kann nicht nur nach Klassen oder Dateien, sondern auch nach IDE-nativen Aktionen gesucht werden.
- Die Tastenkombination Alt + Enter ist universal einsetzbar und ermöglicht unter anderem das Aufrufen der Dokumentation zu verschiedenen Klassen, Refactor, das Generieren von Code uvm.
- Das Arbeiten mit C#-Code ist möglich ohne ständig zwischen Unity und der IDE zu wechseln.
- Die IDE bietet Möglichkeiten für Logging, Debugging und Unit Testing
