### ISSUE TITLE
Valve Index

### ISSUE THREAD

**Issue by MBrill** [VRLAB-HSKL/VRDemos#8]
Die Valve Index sieht als Hardware sehr interessant aus, es ist auch denkbar, dass wir eine Index für das Labor erwerben. 
Deshalb sollten wir überprüfen, ob wir eine Anwendung für die Index mit Hilfe von VIU erstellen können.

**Comment by Jub42** [comment]
VIU bietet die Möglichkeit (siehe Preferences) dem Projekt das SteamVR-Package hinzuzufügen. Es wurde ein Build erstellt und auf einer Valve Index getestet.
